---
title: "Untitled"
author: "Conor Tompkins"
date: "1/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(janitor)

library(cluster)
library(factoextra)
library(dendextend)
```

```{r include=FALSE}
Sys.getenv("CENSUS_API_KEY")
options(tigris_use_cache = TRUE,
        readr.show_progress = FALSE)
```

```{r}
acs_vars <- load_variables(2018, "acs5", cache = TRUE)
```

```{r}
acs_vars %>% 
  filter(str_detect(concept, "MEDIAN AGE BY SEX"),
         str_detect(label, "Total"))

vars_age <- acs_vars %>% 
  filter(name %in% c("B01002_001", "B23013_001"))

vars_race <- acs_vars %>% 
  filter(str_detect(name, "B02001"))

vars_income <- acs_vars %>% 
  filter(name %in% c("B06011_001", "B19025_001", "B19054_001", "B19059_001"))

vars_pop <- acs_vars %>% 
  filter(str_detect(name, "B01003_001"))

vars_benefits <- acs_vars %>% 
  filter(name %in% c("B09010_001", "B19055_001", "B19056_001", "B19057_001", "B19058_001", "B22001_001"))

vars_housing <- acs_vars %>% 
  filter(name %in% c("B25001_001", "B25027_001", "B25040_001", "B25048_001", "B25051_001", "B25070_001", "B25074_001", "B25104_001"))

vars_health <- acs_vars %>% 
  filter(str_detect(name, "B27011"))

vars_education <- acs_vars %>% 
  filter(str_detect(name, "B15003"))
         
vars_employment <- acs_vars %>% 
  filter(str_detect(name, "C18120"))

vars_language <- acs_vars %>% 
  filter(str_detect(name, "B16001"))

vars_other <- acs_vars %>% 
  filter(name %in% c("B28001_001", "B28002_001", "B28010_001", "B28010_007", "B28011_002", "B28011_008"))

vars_all <- bind_rows(vars_age, vars_race, vars_income, vars_pop, vars_benefits, vars_housing, vars_health, vars_education, vars_employment, vars_language, vars_other)
```

```{r}
df_map <- get_acs(variables = "B01002F_001",
                  state = "PA",
                  geography = "tract",
                  geometry = TRUE) %>% 
  select(-c(variable:moe))
```

```{r eval = FALSE}
df_acs <- get_acs(variables = vars_education %>% pull(name) %>% unlist(),
                  state = "PA",
                  geography = "tract",
                  geometry = FALSE) %>% 
  left_join(acs_vars %>% select(name, concept), by = c("variable" = "name")) %>% 
  select(GEOID, NAME, variable, concept, everything()) %>% 
  mutate(concept = make_clean_names(concept),
         concept_short = str_sub(concept, 1, 40)) %>% 
  group_by(variable) %>% 
  mutate(estimate = scale(estimate)) %>% 
  ungroup()

write_csv(df_acs, "output/acs_query_data.csv")
```

```{r}
df_acs <- read_csv("output/acs_query_data.csv",
                   col_types = cols(.default = "c")) %>%
  mutate_at(c("estimate", "moe"), as.numeric)
```

```{r}
df_map %>% 
  left_join(df_acs) %>% 
  ggplot() +
    geom_sf(aes(fill = estimate), color = NA) +
    facet_wrap(~variable, ncol = 1) +
    scale_fill_viridis_c() +
    theme_void()
```

```{r}
df_cluster <- df_acs %>% 
  select(GEOID, variable, estimate) %>% 
  pivot_wider(names_from = variable, values_from = estimate, names_prefix = "var_") %>% 
  remove_empty(which = c("cols"))
```

```{r}
# Dissimilarity matrix
d <- dist(df_cluster, method = "euclidean")

# Hierarchical clustering using Complete Linkage
hc1 <- hclust(d, method = "complete" )

# Plot the obtained dendrogram
plot(hc1, cex = 0.6, hang = -1)
```

```{r}
# Compute with agnes
hc2 <- agnes(df_cluster, method = "complete")

# Agglomerative coefficient
hc2$ac
```

```{r}
# methods to assess
m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")

# function to compute coefficient
ac <- function(x) {
  agnes(df_cluster, method = x)$ac
}

map_dbl(m, ac)
```

```{r}
hc3 <- agnes(df_cluster, method = "ward")
pltree(hc3, cex = 0.6, hang = -1, main = "Dendrogram of agnes") 
```

```{r}
# compute divisive hierarchical clustering
hc4 <- diana(df_cluster)

# Divise coefficient; amount of clustering structure found
hc4$dc

# plot dendrogram
pltree(hc4, cex = 0.6, hang = -1, main = "Dendrogram of diana")
```

```{r}
# Ward's method
hc5 <- hclust(d, method = "ward.D2" )

# Cut tree into 4 groups
sub_grp <- cutree(hc5, k = 8)

# Number of members in each cluster
table(sub_grp)
```

```{r}
df_cluster %>%
  mutate(cluster = sub_grp) %>%
  head()
```

```{r}
plot(hc5, cex = 0.6)
```

```{r}
rect.hclust(hc5, k = 4, border = 2:5)
```

```{r}
fviz_cluster(list(data = df_cluster, cluster = sub_grp))
```

```{r}
df_cluster_map <- df_cluster %>%
  mutate(cluster = as.factor(sub_grp)) %>% 
  select(-contains("var"))

df_map %>% 
  left_join(df_cluster_map) %>% 
  ggplot() +
    geom_sf(aes(fill = cluster), color = "grey")
```
